# Site settings
title: Hillsborough County Hurricane Expo
email: info@hillsboroughcounty.org

description: "The Tampa Bay Hurricane Expo will feature guest speakers, safety demonstrations, emergency vehicle displays, vendors of safety products, and personal disaster preparedness."

tagline: 'Free & Open to the Public'

baseurl: "/hurricaneExpo" # the subpath of your site, e.g. /blog/
url: "http://tampabayhurricaneexpo.com" # the base hostname & protocol for your site

timezone: America/New_York
event_date: 2017-06-03 11:00:00 EST
start_time: 11 a.m.
end_time: 3 p.m.

googleanalytics: 'UA-63036279-2'

collections:
   partners:
      output: false

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "/news/:num"

gems:
 - jekyll-coffeescript
 - jekyll-paginate
