# Site settings
title: Tampa Bay Hurricane Expo
email: info@hillsboroughcounty.org
description: "The Tampa Bay Hurricane Expo will feature guest speakers, safety demonstrations, emergency vehicle displays, vendors of safety products, and personal disaster preparedness."

baseurl: "/hurricaneExpo" # the subpath of your site, e.g. /blog/
url: "http://tampabayhurricaneexpo.com" # the base hostname & protocol for your site

# paginate: 2
# paginate_path: "news/:num"

timezone: America/New_York
event_date: 2015-05-30 10:00:00 EST
end_date: 2015-05-30 16:00:00 EST

# Build settings
markdown: kramdown
